In [1]:
import numpy as np

In [7]:
a = np.array([10, 20, 30, 40, 50])
idx = np.array([3, 0, 4, 1, 2])
a[idx]

array([40, 10, 50, 20, 30])

In [8]:
a = np.array([10, 20, 30, 40, 50])
idx = np.array([0, 0, 2, 2, 4, 4, 1])
a[idx]

array([10, 10, 30, 30, 50, 50, 20])

In [10]:
M = np.array([[ 1,  2,  3],
              [ 4,  5,  6],
              [ 7,  8,  9],
              [10, 11, 12]])
idx = np.array([2, 0, 2])
M[idx]

array([[7, 8, 9],
       [1, 2, 3],
       [7, 8, 9]])

In [11]:
M = np.array([[ 1,  2,  3],
              [ 4,  5,  6],
              [ 7,  8,  9],
              [10, 11, 12]])
idx = np.array([2, 0])

M[:, idx]

array([[ 3,  1],
       [ 6,  4],
       [ 9,  7],
       [12, 10]])

M[perm] = (([[20, 21, 22, 23],
              [ 0, 1, 2, 3],
              [30, 31, 32, 33],
              [10, 11, 12, 13],])